### PR TITLE
[2.0.0] 패키지 기반 모듈화 리팩토링

### LINKED ISSUE #72: [2.0.0] 패키지 기반 모듈화
## 개요

xcproject 에서 작업한 내용들을 패키지로 가져오면서 product와 target을 재정의 하고자 합니다.
또한 ComposableArchitecture 의 observation-beta 브랜치를 의존성으로 추가하면서 Observable Architecture 를 적용합니다.
모듈화 구성에 대한 전반적인 이해는 디자인 섹션의 이미지를 참고해주세요.

## BPM
Package Based Modularization

스크린샷 2023-12-17 오후 2 57 40

```swift
import NoticeUI
import DepartmentUI
```

라이브러리 이름: App
플랫폼 지원버전: iOS 17 이상
Swift 컴파일러 버전: 5.9 이상

### Library
| Product | Targets |
| --- | --- |
| App | NoticeUI, DepartmentUI, SubscriptionUI, SearchUI |

### 3rd Party Dependencies
| Package | Product | Version Rule |
| --- | --- | --- |
| swift-composable-architecture | ComposableArchitecture | observation-beta |
| the-satellite | Satellite | main |

### UIKit
- 공통으로 ColorSet, ComposableArchitecture 들어감

| Target | Dependencies | 
| --- | --- | 
| NoticeUI | NoticeFeatures, SearchFeatures, SubscriptionUI, DepartmentUI, SearchUI |
| SubscriptionUI | SubscriptionFeatures, DepartmentFeatures, DepartmentUI  |
| DepartmentUI | DepartmentFeatures |
| SearchUI | SearchFeatures, NoticeFeatures |

### Features
- 공통으로 Models, KuringLink, ComposableArchitecture 들어감

| Target | Dependencies |
| --- | --- |
| NoticeFeature |  DepartmentFeatures, SearchFeatures, SubscriptionFeatures |
| SubscriptionFeatures | DepartmentFeatures |
| DepartmentFeatures | |
| SearchFeatures | |

### Shared
| Target | Dependencies | 역할 |
| --- | --- | --- |
| ColorSet | 없음 | 코드로 색상 정의 |
| KuringLink | Models, Satellite, ComposableArchitecture | API 네트워크 통신 |
| Models | 없음 | 모델 정의 |

### 디자인

위에 첨부

### 기대효과

생성된 타겟들을 기반으로 새롭게 특정 기능만을 빌드해볼 수 있는 product 생성이 가능.
굳이 하나의 기능을 돌려보기 위해 모든 기능을 빌드할 필요가 없는 환경 구축

## 대안

Observable Architecture 적용에는 약간의 러닝 커브가 있습니다. 이 부분에서 어려움을 느끼신다면 1.4 미만 버전으로 롤백 가능성을 염두해두고 있습니다.

### PR DESCRIPTION
**Pull request by x-0o0**
스크린샷 2023-12-17 오후 2 57 40

- xcproject에서 작업한 코드를 패키지로 이동
- TCA observation-beta 브랜치 적용

```swift
import NoticeUI
import DepartmentUI
```

라이브러리 이름: App
플랫폼 지원버전: iOS 17 이상
Swift 컴파일러 버전: 5.9 이상

### Library
| Product | Targets |
| --- | --- |
| App | NoticeUI, DepartmentUI, SubscriptionUI, SearchUI |

### 3rd Party Dependencies
| Package | Product | Version Rule |
| --- | --- | --- |
| swift-composable-architecture | ComposableArchitecture | observation-beta |
| the-satellite | Satellite | main |

### UIKit
- 공통으로 ColorSet, ComposableArchitecture 들어감

| Target | Dependencies | 
| --- | --- | 
| NoticeUI | NoticeFeatures, SearchFeatures, SubscriptionUI, DepartmentUI, SearchUI |
| SubscriptionUI | SubscriptionFeatures, DepartmentFeatures, DepartmentUI  |
| DepartmentUI | DepartmentFeatures |
| SearchUI | SearchFeatures, NoticeFeatures |

### Features
- 공통으로 Models, KuringLink, ComposableArchitecture 들어감

| Target | Dependencies |
| --- | --- |
| NoticeFeature |  DepartmentFeatures, SearchFeatures, SubscriptionFeatures |
| SubscriptionFeatures | DepartmentFeatures |
| DepartmentFeatures | |
| SearchFeatures | |

### Shared
| Target | Dependencies | 역할 |
| --- | --- | --- |
| ColorSet | 없음 | 코드로 색상 정의 |
| KuringLink | Models, Satellite, ComposableArchitecture | API 네트워크 통신 |
| Models | 없음 | 모델 정의 |

### CODE REVIEW

**Comment by x-0o0** [comment]
### 남은 작업

- [x] xcodeproj 에 적용

**Comment by x-0o0** [comment]
TCA의 Observable Architecture 적용

https://github.com/ku-ring/ios-app/discussions/73

**Review by sunshiningsoo — APPROVED** [review]
감사합니다!

**Pull request merged**
